name: Comment Test
on: [issue_comment]

jobs:
  sm_deploy:
    if: github.event.issue.pull_request != null &&  contains(github.event.comment.body, '/test') && (github.actor == 'hunkim' || github.actor == 'ygg')
    runs-on: ubuntu-latest
    steps:
       steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      
    - name: Install requirements
      run: pip install --requirement requirements.txt

    - name: Deploy
      id: sm_deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python comment.py